### ISSUE TITLE
password

### ISSUE THREAD

**Issue by GizatulinVitaliy** [Byndyusoft/ByndyuSoft.Dotnet.Infrastructure#11]
Hello.  

var password = new Password("Password123456123456");

Assert.IsTrue(password.Check("Password123456123456"));
Assert.IsTrue(password.Check("Password123456123456123456123456"));
Assert.IsTrue(password.Check("Password123123456456123123456456"));
Assert.IsTrue(password.Check("Password123456"));
Assert.IsTrue(password.Check("Password1123456"));

**Comment by xctmaf** [comment]
#14

**Comment by razonrus** [comment]
closed by https://github.com/ByndyuSoft/ByndyuSoft.Dotnet.Infrastructure/pull/14
