### ISSUE TITLE
How to use FormHandler when I create new entity. 

### ISSUE THREAD

**Issue by mfilippov** [ByndyuSoft/ByndyuSoft.Dotnet.Infrastructure#15]
When I create a new entity from a form, I need to redirect to a page with the new entity but I, can't do it because I don't have an id before the Form handled. What is the correct way to create a new entity in your infrastructure?

**Comment by Satem** [comment]
The only plausible way to IFromHandler that I see is:

**Comment by Satem** [comment]
The only plausible way to IFromHandler that I see is:
1. Invoke the "Execute" method: <code>handler.Execute(form);</code>
2. Set the "Id" (or similar) property of the form inside the IFromHandler implimentation

**Comment by Satem** [comment]
The only plausible way to IFromHandler that I see is:
 
1. Invoke the "Execute" method: <code>handler.Execute(form);</code>
2. Set the "Id" (or similar) property of the form inside the IFormHandler implimentation
3. Return RedirectToRouteResult as ActionResult: <code>return RedirectToAction(redirectActionName, redirectControllerName, new {form.Id});</code>

**Comment by mfilippov** [comment]
@Satem Thank you. For the answer, we already use this way :)
