### ISSUE TITLE
Bug Conventions 

### ISSUE THREAD

**Issue by artem-kovalev** [ByndyuSoft/ByndyuSoft.Dotnet.Infrastructure#4]
Hello. I dont know it is bug   Infrastructure.NHibernate.Conventions or NHibernate. 

Entity Example
public class Client : IEntity
{
        public virtual int Id { get; set; }
        public virtual string Address { get; set; }
        public virtual IEnumerable&lang;Phone&rang; Phones { get; set; }  
}
public class Phone : IEntity
{
   public virtual int Id { get; set; }
   public virtual string Number { get; set; }
}

NHiberate generate 2 DataBase Enitity. CLIENT and PHONE.

But use these class is not possible, because automapping throws exception: "Could not find property nor field 'phones' in class 'Client'"

**Comment by AlexanderByndyu** [comment]
Correct code is:
public class Client : IEntity
{
private ICollection<Phone> phones = new List<Phone>();

public virtual int Id { get; set; }
public virtual string Address { get; set; }
public virtual IEnumerable〈Phone〉 Phones 
{ 
    get{ return phones; } 
}
}
public class Phone : IEntity
{
public virtual int Id { get; set; }
public virtual string Number { get; set; }
}
